source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

xcodeproj 'VideoSee'

target :VideoSee do
pod 'MagicalRecord'
pod 'PureLayout'
pod 'MBProgressHUD'
pod 'MBLocationManager'
pod 'GoogleMaps'
pod 'AFNetworking'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end